Rewrite library to an ES2015 code style
athombv/node-castv2 pull request #1
Opened 2018-08-30 15:36 UTC by elisaado

2018-09-10 17:41 UTC, WeeJeWel requested changes

2018-09-10 17:41 UTC, WeeJeWel commented on lib/channel.js
> +let EventEmitter = require('events');
use const

2018-09-10 17:41 UTC, WeeJeWel commented on lib/channel.js
> +let EventEmitter = require('events');
+ `'use strict';` on top

2018-09-10 17:41 UTC, WeeJeWel commented on lib/channel.js
> +function encode(data, encoding) {
make static method

2018-09-10 17:41 UTC, WeeJeWel commented on lib/channel.js
> +        const onmessage = (sourceId, destinationId, namespace, data) => {
Move to class method `_onMessage`

2018-09-10 17:41 UTC, WeeJeWel commented on lib/channel.js
> +        const onmessage = (sourceId, destinationId, namespace, data) => {
`this._onMessage = this._onMessage.bind(this)`

2018-09-10 17:41 UTC, WeeJeWel commented on lib/client.js
> +    connect(options) {
add `async` because a promise is returned

2018-09-10 17:41 UTC, WeeJeWel commented on lib/client.js
> +    connect(options) {
`connect({ host })`

2018-09-10 17:41 UTC, WeeJeWel commented on lib/client.js
> +    send(sourceId, destinationId, namespace, data) {
deconstruct

2018-09-10 17:41 UTC, WeeJeWel commented on lib/client.js
> +            namespace: namespace
`namespace,`

2018-09-10 17:41 UTC, WeeJeWel commented on lib/packet-stream-wrapper.js
> +    let self = this;
Use arrow methods

2018-09-10 17:41 UTC, WeeJeWel commented on lib/proto.js
> +const ProtoBuf  = require("protobufjs");
single quotes

2018-09-10 17:41 UTC, WeeJeWel commented on lib/proto.js
> +let builder = ProtoBuf.loadProtoFile(__dirname + "/cast_channel.proto");
Use `path.join(__dirname, 'cast_channel.proto')`

2018-09-10 17:41 UTC, WeeJeWel commented on lib/proto.js
> +      let msg = new extensions[message](data);
lowercase class

2018-09-10 17:41 UTC, WeeJeWel commented on lib/proto.js
> +      let msg = new extensions[message](data);
```
const Extension = extensions[message]
const msg = new Extension(data)
```

2018-09-10 17:41 UTC, WeeJeWel commented on lib/client.js
> +    close() {
rename to `disconnect()`

2018-09-24 13:14 UTC, elisaado commented
@WeeJeWel Could you review my latest changes?

2018-09-25 09:53 UTC, WeeJeWel approved these changes

2018-09-26 06:26 UTC, elisaado commented
I do not have write access to this repository :sweat_smile:

2018-09-26 13:13 UTC, WeeJeWel commented
Now you do!

2018-09-27 07:28 UTC, merged